config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new' 
  resources :users
  post '/auth/:provider/callback', to: 'sessions#create'
  resource :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates :email, email: true, uniqueness: {case_sensitive: false}
  validates :password, length: { in: 4..100 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user 
  def current_user 
    User.find_by_id(session[:current_user_id]) if session[:current_user_id]
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :verify_authenticity_token, only: :create

  def create
    #omniauth users
    if params[:provider]
      @user = User.find_by(
        email: params[:email],
        provider: params[:provider]
      )
      if !@user 
        @user = User.create!(
          email: params[:email],
          provider: params[:provider],
          password: SecureRandom.hex #generating random password since they will authenticate through OmniAuth
        )
      end
    else 
      #not omniauth 

      @user = User.find_by_email(params[:email])
      
      if !@user || !@user.authenticate(params[:password])
        flash[:error] = "We don't know you!"
        redirect_to root_path
        return
      end
    end
    session[:current_user_id] = @user.id
    redirect_to root_path
  end

  def new
    
  end

  def destroy
    session[:current_user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.all
    #get all users and show their emails
  end

  def new
    @user = User.new 
  end

  def create

    @user = User.new(user_params)
    @user.save
    if !@user.valid?
      render "new"
      return
    end
    redirect_to user_path(@user)
    
    # TODO: create user
    #redirect to users path for that user 
  end

  def show 
    @user = User.find(params[:id])

    # TODO: show user email 
  end
private 

  def user_params
    params.require(:user).permit(:email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Knit</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user %>
     <div><%= link_to "Sign Out", sessions_path, method: :delete %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/index.html.erb
<% @users.each do |u| %>
  <%= u.email %>

<% end %>

app/views/users/new.html.erb
<h1> Create a new account </h1>
<%= form_tag users_path do %>
  <% if @user.errors.any? %>
    <div>
     <ul>
      <% @user.errors.full_messages.each do |e| %>
        <li><%= e %></li>
      <% end %>
     </ul>
    </div>
  <% end %>
  
  <label>Email:</label><br>
  <%= text_field_tag :'user[email]' %><br>
  <label>Password:</label><br>
  <%= password_field_tag :'user[password]' %><br>
  <%= submit_tag "Submit" %>

  <% end %>

app/views/users/show.html.erb
<%= @user.email %>